In [80]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)

In [81]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

 FASE 1;
 EDA: EXPLORATORY DATA ANALYSIS
     nos ayuda a detectar errores, patrones y posibles problemas

primer vistazo

In [82]:
df_alquileres=pd.read_csv("listings.csv")

display(df_alquileres.head(2))
print("="*100)
display(df_alquileres.tail(2))
print("="*100)
display(df_alquileres.sample(2))

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,18674,Huge flat for 8 people close to Sagrada Familia,71615,1462508358342835057,Mireia,Eixample,la Sagrada Família,41.40556,2.17262,Entire home/apt,NaN,1,54,2025-11-19,0.35,24,115,9,Spain - National registration number<br />ESFC...
1,2031134,Sagrada Familia-auditorium. FREE WI-FI.,9100900,1462794940868112780,Miguel,Eixample,el Fort Pienc,41.40001,2.18416,Entire home/apt,NaN,2,453,2025-12-02,3.16,1,294,52,Barcelona - Regional registration number<br />...

====================================================================================================

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
18175,1574678224497628954,Cuarto privado para estancias cortas,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.386200,2.16769,Private room,NaN,2,0,NaN,NaN,5,345,0,Barcelona - Regional registration number<br />...
18176,1574760542225568017,comfortable sunny quiet central located,258156372,1469363937744404825,Jorge Antonio,Ciutat Vella,el Raval,41.381548,2.17034,Entire home/apt,NaN,7,0,NaN,NaN,2,15,0,Spain - National registration number<br />Exem...

====================================================================================================

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
7707,52278861,Private Suite w/Bathroom + Private Terrace,1503151,1462547578548271917,Laia,Ciutat Vella,el Raval,41.38396,2.17076,Private room,NaN,32,0,NaN,NaN,75,258,0,NaN
8092,53857989,Loft con Gran Terraza,342498888,1469673841690820980,B&F Accommodations,Les Corts,les Corts,41.38954,2.14326,Entire home/apt,NaN,1,8,2025-09-24,0.2,19,156,2,Spain - National registration number<br />ESHF...

In [83]:
print(f"el DataFrame alquileres tiene {df_alquileres.shape[0]} filas y {df_alquileres.shape[1]} columnas")

el DataFrame alquileres tiene 18177 filas y 19 columnas

In [84]:
df_alquileres.info()

<class 'pandas.DataFrame'>
RangeIndex: 18177 entries, 0 to 18176
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              18177 non-null  int64
 1   name                            18177 non-null  str
 2   host_id                         18177 non-null  int64
 3   host_profile_id                 18177 non-null  int64
 4   host_name                       18171 non-null  str
 5   neighbourhood_group             18177 non-null  str
 6   neighbourhood                   18177 non-null  str
 7   latitude                        18177 non-null  float64
 8   longitude                       18177 non-null  float64
 9   room_type                       18177 non-null  str
 10  price                           0 non-null      float64
 11  minimum_nights                  18177 non-null  int64
 12  number_of_reviews               18177 non-null  int64
 13  last_review                     13095 non-null  str
 14  reviews_per_month               13095 non-null  float64
 15  calculated_host_listings_count  18177 non-null  int64
 16  availability_365                18177 non-null  int64
 17  number_of_reviews_ltm           18177 non-null  int64
 18  license                         11014 non-null  str
dtypes: float64(4), int64(8), str(7)
memory usage: 2.6 MB

In [85]:
# la columna price esta completamente vacia
# faltan valores en host_name, last_review y review_per_month
# license, hay una diferencia de 7000, 
# cambiar last reviw a time
# comprobar si las columnas host id y host profile id son lo mismo

In [86]:
df_alquileres.columns

Index(['id', 'name', 'host_id', 'host_profile_id', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

In [87]:
col_nuevas_alquileres = {col: col.lower().replace(" ", "_").replace(".", "_").replace("-", "_") for col in df_alquileres.columns}

col_nuevas_alquileres

{'id': 'id',
 'name': 'name',
 'host_id': 'host_id',
 'host_profile_id': 'host_profile_id',
 'host_name': 'host_name',
 'neighbourhood_group': 'neighbourhood_group',
 'neighbourhood': 'neighbourhood',
 'latitude': 'latitude',
 'longitude': 'longitude',
 'room_type': 'room_type',
 'price': 'price',
 'minimum_nights': 'minimum_nights',
 'number_of_reviews': 'number_of_reviews',
 'last_review': 'last_review',
 'reviews_per_month': 'reviews_per_month',
 'calculated_host_listings_count': 'calculated_host_listings_count',
 'availability_365': 'availability_365',
 'number_of_reviews_ltm': 'number_of_reviews_ltm',
 'license': 'license'}

In [88]:
df_alquileres

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,18674,Huge flat for 8 people close to Sagrada Familia,71615,1462508358342835057,Mireia,Eixample,la Sagrada Família,41.405560,2.17262,Entire home/apt,NaN,1,54,2025-11-19,0.35,24,115,9,Spain - National registration number<br />ESFC...
1,2031134,Sagrada Familia-auditorium. FREE WI-FI.,9100900,1462794940868112780,Miguel,Eixample,el Fort Pienc,41.400010,2.18416,Entire home/apt,NaN,2,453,2025-12-02,3.16,1,294,52,Barcelona - Regional registration number<br />...
2,4415694,DEEP PURPLE - RAMBLES,12385333,1462886557122269531,Yolanda,Sants-Montjuïc,el Poble Sec,41.372300,2.16441,Entire home/apt,NaN,3,182,2025-11-09,1.39,2,115,11,Barcelona - Regional registration number<br />...
3,4415780,"Double Room ""Barcelona""",4990426,1462670184572182763,Judith,Gràcia,la Vila de Gràcia,41.406670,2.16152,Private room,NaN,1,5,2016-10-19,0.04,1,0,0,NaN
4,5064035,Lovely 2 BD with terrace and wifi,1744516,1462577289140824079,Silvia & Luís,Gràcia,la Vila de Gràcia,41.399960,2.16339,Entire home/apt,NaN,3,128,2025-11-30,0.99,39,222,23,Spain - National registration number<br />ESHF...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18172,1574656863638461043,Habitación económica con wifi,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.386120,2.16913,Private room,NaN,2,0,NaN,NaN,5,335,0,Barcelona - Regional registration number<br />...
18173,1574664158072287966,Habitación básica pero confortable,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.388040,2.16863,Private room,NaN,2,0,NaN,NaN,5,352,0,Barcelona - Regional registration number<br />...
18174,1574674722789145942,Habitación práctica cerca del centro,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.388090,2.16891,Private room,NaN,2,0,NaN,NaN,5,342,0,Barcelona - Regional registration number<br />...
18175,1574678224497628954,Cuarto privado para estancias cortas,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.386200,2.16769,Private room,NaN,2,0,NaN,NaN,5,345,0,Barcelona - Regional registration number<br />...
18176,1574760542225568017,comfortable sunny quiet central located,258156372,1469363937744404825,Jorge Antonio,Ciutat Vella,el Raval,41.381548,2.17034,Entire home/apt,NaN,7,0,NaN,NaN,2,15,0,Spain - National registration number<br />Exem...

In [89]:
df_alquileres.describe()

,id,host_id,host_profile_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,1.817700e+04,1.817700e+04,1.817700e+04,18177.000000,18177.000000,0.0,18177.000000,18177.000000,13095.000000,18177.000000,18177.000000,18177.000000
mean,6.447131e+17,2.095417e+08,1.467412e+18,41.392062,2.166841,NaN,16.592507,54.563184,1.423378,68.490235,209.572152,11.200638
std,6.114387e+17,2.166172e+08,9.983765e+15,0.013635,0.017620,NaN,31.589899,116.779279,2.228578,129.195119,130.313696,24.999374
min,1.867400e+04,3.073000e+03,1.462506e+18,41.350673,2.092760,NaN,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,3.067338e+07,1.178986e+07,1.462709e+18,41.381304,2.156450,NaN,1.000000,0.000000,0.190000,2.000000,88.000000,0.000000
50%,7.246708e+17,1.310289e+08,1.465908e+18,41.390170,2.167630,NaN,3.000000,5.000000,0.710000,9.000000,245.000000,1.000000
75%,1.222431e+18,3.621554e+08,1.469674e+18,41.401185,2.177600,NaN,31.000000,52.000000,2.150000,52.000000,328.000000,14.000000
max,1.574761e+18,7.320408e+08,1.568799e+18,41.462243,2.221830,NaN,1124.000000,2042.000000,99.790000,549.000000,365.000000,938.000000

In [90]:
df_alquileres.describe().T

,count,mean,std,min,25%,50%,75%,max
id,18177.0,6.447131e+17,6.114387e+17,1.867400e+04,3.067338e+07,7.246708e+17,1.222431e+18,1.574761e+18
host_id,18177.0,2.095417e+08,2.166172e+08,3.073000e+03,1.178986e+07,1.310289e+08,3.621554e+08,7.320408e+08
host_profile_id,18177.0,1.467412e+18,9.983765e+15,1.462506e+18,1.462709e+18,1.465908e+18,1.469674e+18,1.568799e+18
latitude,18177.0,4.139206e+01,1.363455e-02,4.135067e+01,4.138130e+01,4.139017e+01,4.140118e+01,4.146224e+01
longitude,18177.0,2.166841e+00,1.761965e-02,2.092760e+00,2.156450e+00,2.167630e+00,2.177600e+00,2.221830e+00
price,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
minimum_nights,18177.0,1.659251e+01,3.158990e+01,1.000000e+00,1.000000e+00,3.000000e+00,3.100000e+01,1.124000e+03
number_of_reviews,18177.0,5.456318e+01,1.167793e+02,0.000000e+00,0.000000e+00,5.000000e+00,5.200000e+01,2.042000e+03
reviews_per_month,13095.0,1.423378e+00,2.228578e+00,1.000000e-02,1.900000e-01,7.100000e-01,2.150000e+00,9.979000e+01
calculated_host_listings_count,18177.0,6.849023e+01,1.291951e+02,1.000000e+00,2.000000e+00,9.000000e+00,5.200000e+01,5.490000e+02
availability_365,18177.0,2.095722e+02,1.303137e+02,0.000000e+00,8.800000e+01,2.450000e+02,3.280000e+02,3.650000e+02
number_of_reviews_ltm,18177.0,1.120064e+01,2.499937e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.400000e+01,9.380000e+02

In [91]:
# VALORES FALTANTES
df_nulos=(df_alquileres.isna().sum().sort_values(ascending=False)) # me enseña los nulos
df_nulos

price                             18177
license                            7163
reviews_per_month                  5082
last_review                        5082
host_name                             6
id                                    0
name                                  0
host_id                               0
neighbourhood                         0
neighbourhood_group                   0
host_profile_id                       0
room_type                             0
longitude                             0
latitude                              0
number_of_reviews                     0
minimum_nights                        0
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
dtype: int64

In [92]:
# DUPLICADOS

df_alquileres.duplicated().sum()
df_alquileres.duplicated(subset=["id"]).sum() # no tenemos duplicados

np.int64(0)

In [93]:
# COLUMNAS CATEGORICAS
df_cat=(df_alquileres.select_dtypes(include="str").columns)
df_cat

Index(['name', 'host_name', 'neighbourhood_group', 'neighbourhood',
       'room_type', 'last_review', 'license'],
      dtype='str')

In [ ]:
# vemos valores, detectar inconsistencias
for col in df_alquileres.select_dtypes(include='object').columns:
    print(f"\nColumna: {col}")
    print(df_alquileres[col].value_counts().head(10))

Columna: name
name
Co-living Ample 24, Barcelona                       32
Habitación con baño privado                         13
Penthouse San Gervasi ático David                   12
BarcelonaForRent The Central Place                  11
Double room with balcony                            11
Cozy Apartment Joan Austria                         11
Habitación doble con litera en espacio Co-living     9
Premium 2 br design flat Merce                       9
2 Bedroom Apartment with balcony                     9
Big double room with balcony                         8
Name: count, dtype: int64

Columna: host_name
host_name
Ukio          549
David         437
Jacob         429
Silvia        346
Adria         321
SweetInn      264
Alvaro        261
Arnau         227
Enrique       202
Blueground    175
Name: count, dtype: int64

Columna: neighbourhood_group
neighbourhood_group
Eixample               6659
Ciutat Vella           4120
Sants-Montjuïc         1766
Sant Martí             1634
Gràcia                 1548
Sarrià-Sant Gervasi    1117
Horta-Guinardó          460
Les Corts               405
Sant Andreu             278
Nou Barris              190
Name: count, dtype: int64

Columna: neighbourhood
neighbourhood
la Dreta de l'Eixample                   2404
el Raval                                 1330
el Barri Gòtic                           1167
Sant Pere, Santa Caterina i la Ribera    1141
la Vila de Gràcia                        1056
la Sagrada Família                       1047
l'Antiga Esquerra de l'Eixample          1006
Sant Antoni                               947
el Poble Sec                              823
la Nova Esquerra de l'Eixample            766
Name: count, dtype: int64

Columna: room_type
room_type
Entire home/apt    11745
Private room        6216
Shared room          114
Hotel room           102
Name: count, dtype: int64

Columna: last_review
last_review
2025-11-30    500
2025-12-08    346
2025-11-23    339
2025-12-07    300
2025-11-24    290
2025-12-01    270
2025-11-29    267
2025-11-28    218
2025-11-27    177
2025-11-16    176
Name: count, dtype: int64

Columna: license
license
Spain - National registration number<br />Exempt                                                                                                                        78
Barcelona - Regional registration number<br />HUTB-000000                                                                                                               38
Barcelona - Regional registration number<br />HUTB012407                                                                                                                24
Spain - National registration number<br />ESFCNT00000805900063465600000000000000000000000000001                                                                         23
Barcelona - Regional registration number<br />AJ000593<br /><br />Spain - National registration number<br />Exempt                                                      22
Barcelona - Regional registration number<br />HB-000087                                                                                                                 20
Barcelona - Regional registration number<br />HUTB-012457                                                                                                               18
Spain - National registration number<br />ESFCTU00000807200005651800000000000000000000000071101<br /><br />Barcelona - Regional registration number<br />HUTB-007110    18
Barcelona - Regional registration number<br />HB-004525                                                                                                                 16
Barcelona - Regional registration number<br />AJ000517<br /><br />Spain - National registration number<br />Exempt                                                      16
Name: count, dtype: int64

C:\Users\Barbra\AppData\Local\Temp\ipykernel_18028\2029707536.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_alquileres.select_dtypes(include='object').columns:

se modifica la columna last_review a data time, para mejor comprension de la misma.

In [98]:
df_alquileres['last_review'] = pd.to_datetime(df_alquileres['last_review'])
df_alquileres.info()

<class 'pandas.DataFrame'>
RangeIndex: 18177 entries, 0 to 18176
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              18177 non-null  int64
 1   name                            18177 non-null  str
 2   host_id                         18177 non-null  int64
 3   host_profile_id                 18177 non-null  int64
 4   host_name                       18171 non-null  str
 5   neighbourhood_group             18177 non-null  str
 6   neighbourhood                   18177 non-null  str
 7   latitude                        18177 non-null  float64
 8   longitude                       18177 non-null  float64
 9   room_type                       18177 non-null  str
 10  price                           0 non-null      float64
 11  minimum_nights                  18177 non-null  int64
 12  number_of_reviews               18177 non-null  int64
 13  last_review                     13095 non-null  datetime64[us]
 14  reviews_per_month               13095 non-null  float64
 15  calculated_host_listings_count  18177 non-null  int64
 16  availability_365                18177 non-null  int64
 17  number_of_reviews_ltm           18177 non-null  int64
 18  license                         11014 non-null  str
dtypes: datetime64[us](1), float64(4), int64(8), str(6)
memory usage: 2.6 MB

1.CUANTOS ALOJAMIENTOS UNICOS CONTIENE EL DATAFRAME?

In [ ]:
df_alquileres["id"].nunique() # no hay duplicados

18177

2.QUE TIPO DE ALOJAMIENTOS EXISTEN Y CUAL ES EL MAS COMUN?

In [ ]:
df_alquileres["room_type"].value_counts() # la mayoria de alojamientos son viviendas completas, ya sea casa o apartamento.

room_type
Entire home/apt    11745
Private room        6216
Shared room          114
Hotel room           102
Name: count, dtype: int64

3.COMO SE DISTRIBUYEN POR BARRIOS O ZONA?